import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className='flex h-16  bg-yellow-300'>
          <form action="/items" className='m-auto gap-4 flex max-w-screen-lg flex-1'>
            <input className="h-8 px-2 flex-1" name='search' type="text" placeholder='Buscar productos, marcas y más...' />
             
            <button className="h-8 bg-gray-300 px-2 py-1 text-slate-500" type='submit'>Buscar</button>
          </form>
        </header>
        <main className='m-auto max-w-screen-lg p-4'>{children}</main>
      </body>
    </html>
  )
}
